[tool.poetry]
name = "fit-blocks"
version = "1.0.0"
description = ""
authors = ["Zzzoley <mzzzoley@gmail.com>"]
license = "N/A"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
